IF DB_ID('LMS_IdentityDb') IS NULL CREATE DATABASE LMS_IdentityDb;
GO
IF DB_ID('LMS_StudentDb') IS NULL CREATE DATABASE LMS_StudentDb;
GO
IF DB_ID('LMS_CourseDb') IS NULL CREATE DATABASE LMS_CourseDb;
GO

